<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Oander\CustomerProfile\Block\View\Element\Html\Links */
?>
<div class="block profile-user-profile d-none d-md-flex">
    <p class="profile-user-profile__monogram" aria-hidden="true"><span><?= $block->getMonogram()?><span</p>
    <div>
        <h2 class="h3 profile-user-profile__name"><b><?=$block->getCustomerFullName()?></b></h2>
        <p class="profile-user-profile__mail"><?=$block->getCustomerEmail()?></p>
    </div>
</div>
<div class="block account-nav">
    <div class="title abs-visually-hidden-mobile-m">
        <strong><?php /* @escapeNotVerified */ echo __('My Account'); ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav collapse in" id="account-nav">
            <ul class="nav items account-nav__ul">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
<script type="text/javascript">
    require(['oander.account-navigation']);
</script>