<?php
/** @var $this \Oander\PosLocations\Block\ListBlock */
?>
<?php $shopCollection = $this->getAllShops(); ?>
<?php $shops = $shopCollection->getItems(); ?>
<?php if ($shopCollection->getSize() > 0): ?>
    <h1><?php echo __('Locations'); ?></h1>

    <?php echo $this->getChildBlock('google_maps')->setData('shops', $shops)->toHtml(); ?>

    <div class="locations-list">
        <?php /** @var \Oander\PosLocations\Api\Data\ShopInterface $shop */ ?>
        <?php foreach ($shops as $shop): ?>
            <div class="location-item row">
                <div class="col-md-3 col-lg-2 col-image hidden-sm-down">
                    <a href="<?php echo $shop->getShopLink(); ?>" class="location-item__image">
                        <img class="img-fluid" src="<?php echo $shop->getImageUrl(); ?>" /></a>
                </div>
                <div class="col-md-9 col-lg-10 col-middle">
                    <div>
                        <div class="location-meta">
                            <h2 class="location-meta__title">
                                <a href="<?php echo $shop->getShopLink(); ?>"><?php echo $shop->getTitle(); ?></a></h2>
                            <?php if ($shop->getShopTag() != ''): ?>
                                <div class="location-meta__tag"><?php echo $shop->getShopTag(); ?></div>
                            <?php endif; ?>
                        </div>
                        <div class="location-footer">
                            <?php if ($shop->getAddress()) : ?>
                                <address class="location-footer__address"><?php echo $shop->getAddress(); ?></address>
                            <?php endif; ?>
                            <?php if ($shop->getPhoneNumber()) : ?>
                                <div class="location-footer__phone"><?php echo $shop->getPhoneNumber(); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="hidden-sm-down actions">
                        <a href="<?php echo $shop->getShopLink(); ?>" class="action dark"><?php echo __('Learn more'); ?></a>
                    </div>
                    <a href="<?php echo $shop->getShopLink(); ?>" class="more-link hidden-md-up"><i class="icon icon-chevron-right"></i> </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
