<?php
/**
 * @var $block \Oander\SalesforceLoyalty\Block\SuccessPage\LoyaltySubscribe
 */
?>
<?=  $block->getLayout()
    ->createBlock('Oander\SalesforceLoyalty\Block\SuccessPage\LoyaltyMarketing')
    ->setTemplate('Oander_SalesforceLoyalty::successpage/loyalty-marketing.phtml')
    ->toHtml();
?>
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <form
            id="registration"
            action="<?= $block->getActionUrl()?>"
            class="checkout-success-registration loyalty-registration success-page"
        >
            <div class="form-group">
                <?=  $block->getLayout()
                    ->createBlock('Oander\SalesforceLoyalty\Block\SuccessPage\Agreements')
                    ->setTemplate('Magento_Customer::form/register-agreements.phtml')
                    ->toHtml();
                ?>
            </div>
            <input
                id="loyalty-registration"
                type="submit"
                class="action primary"
                value="<?= __('Loyalty subscription')?>"
                disabled
            >
            <script type="text/javascript">
                require(['jquery'], function($) {
                    $(function() {
                        $('#registration.loyalty-registration .checkbox').on('change', function() {
                            if ($(this).is(':checked')) {
                                $('#loyalty-registration').removeAttr('disabled');
                            } else {
                                $('#loyalty-registration').attr('disabled', 'disabled');
                            }
                        });
                    });
                });
            </script>
        </form>
        <div class="reg-messages messages">
            <div class="message"></div>
        </div>
    </div>
</div>