<?php

$code = $block->escapeHtml($block->getMethodCode());
$cards = $block->getCustomerCards();

?>
<fieldset id="payment_form_stripe_payments" class="stripe-payments standard-form admin__fieldset indent-target stripe-new" style="display:none;">

<fieldset class="admin__fieldset payment-method stripe-new stripe-payments" id="payment_form_stripe_payments_payment">

  <?php if (!empty($cards)): ?>
    <div class="stripe-payments-saved-cards-section" id="saved-cards">
      <?php foreach ($cards as $key => $card): ?>
        <div class="stripe-payments-saved-card">
          <input type="radio" name="payment[cc_saved]" class="select"
                value="<?php echo $card->id . ':' . $card->brand . ':' . $card->last4; ?>" id="<?php echo $card->id; ?>"
            >
          <label for="<?php echo $card->id; ?>">
            <span class="type <?php echo $card->brand ?>">
                <?php echo (empty($card->brand) ? __('Card') : $block->cardType($card->brand)); ?>
            </span>
            <span class="last4 stripe-payments-fade"><?php echo __('ending in'); ?> <?php echo $card->last4; ?></span>
            <span class="exp stripe-payments-fade"><?php echo __('expires'); ?>
                <?php echo str_pad($card->exp_month,2,'0',STR_PAD_LEFT); ?>/<?php echo $card->exp_year; ?>
            </span>
          </label>
        </div>
      <?php endforeach; ?>

      <div>
        <input type="radio" name="payment[cc_saved]" value="new_card" class="select" id="new_card" checked="checked">
        <label for="new_card">
          <span class="type"><?php echo __('Use a new card'); ?></span>
        </label>
      </div>
    </div>
  <?php endif; ?>

  <?php echo $block->getLayout()->createBlock('StripeIntegration\Payments\Block\StripeElements')->toHtml(); ?>

  <?php if ($block->showSaveCardInAdmin()): ?>
  <div class="field admin__field stripe-new">
    <label class="admin__field-label" for="stripe_payments_cc_save">
      <input type="checkbox"
        title="<?php echo $block->escapeHtml(__('Save card for future purchases')); ?>"
        class="admin__control-cc-save stripe-input"
        id="stripe_payments_cc_save"
        name="payment[cc_save]"
        <?php echo $block->getSaveCardsChecked(); ?>/>
      <span><?php echo $block->escapeHtml(__('Save card for future purchases')); ?></span>
    </label>
  </div>
  <?php endif; ?>

</fieldset>

<script type="text/javascript">
  require(['domReady!', 'prototype', 'mage/mage'], function(domReady, $) {
      var params = <?php echo $block->config->getStripeParams(); ?>;
      initStripe(params, function(err)
      {
        if (err)
        {
          alert(err);
          return;
        }
        // Disable server side card validation when Stripe.js is enabled
        if (typeof AdminOrder != 'undefined' && AdminOrder.prototype.loadArea && typeof AdminOrder.prototype._loadArea == 'undefined')
        {
          AdminOrder.prototype._loadArea = AdminOrder.prototype.loadArea;
          AdminOrder.prototype.loadArea = function(area, indicator, params)
          {
            if (typeof area == "object" && area.indexOf('card_validation') >= 0)
              area = area.splice(area.indexOf('card_validation'), 0);

            if (area.length > 0)
              return this._loadArea(area, indicator, params);
          };
        }

        stripe.initAdminStripeJs();
        stripe.isAdmin = true;
        stripe.initAdminEvents();
        stripe.initStripeElements(params.locale);
      });
  });
</script>

</fieldset>
