<?php
/**
 * Oander_WonderWidgetNews
 *
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php /** @var $this \Oander\WonderWidgetNews\Block\News */?>

<div class="widget-block block oander-wonder-widget-basic oander-wonder-widget-timed" style="display:none" data-visible-from="<?= $this->getVisibleFrom() ?>" data-visible-to="<?= $this->getVisibleTo() ?>">
    <div class="content">
        <?php if ($this->getImage()): ?>
            <div class="image-wrapper" style="background-image: url('<?php echo $this->getImage(); ?>'); background-repeat: no-repeat;">
                <?php if ($this->getLink()): ?>
                    <a href="<?php echo $this->getLink(); ?>" class="link-overlay">
                        <img src="<?php echo $this->getImage(); ?>" alt="<?php echo $this->getImageAlt() ?? $this->getTitle() ?>" />
                    </a>
                <?php else: ?>
                    <img src="<?php echo $this->getImage(); ?>" alt="<?php echo $this->getImageAlt() ?? $this->getTitle() ?>" class="image" />
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <div class="caption <?php echo ($this->getDescription()) ? 'has-description' : 'no-description' ; ?>">
            <?php if ($this->getTitle()): ?>
                <h2 class="widget-title">
                    <?php if ($this->getLink()): ?>
                        <a href="<?php echo $this->getLink(); ?>" class="widget-title-link">
                            <?php echo $this->getTitle(); ?><i class="icon icon-arrow-right"></i>
                        </a>
                    <?php else: ?>
                        <?php echo $this->getTitle(); ?>
                    <?php endif; ?>
                </h2>
            <?php endif; ?>

            <?php if ($this->getDescription()): ?>
                <div class="description hidden-md-down">
                    <?php echo $this->getDescription(); ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getLink()): ?>
                <div class="link hidden-md-down">
                    <a href="<?php echo $this->getLink(); ?>"><?php echo __('Read More') ?> <i class="icon icon-arrow-right"></i></a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['oanderWonderWidgetTimedDisplay']);
</script>
