<?php
/**
 * Oander_WarehouseManager
 *
 * @author  Tamas Vegvari <tamas.vegvari@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php use Oander\WarehouseManager\Enum\ProductStock\Availability; ?>
<?php use Oander\WarehouseManager\Enum\ProductStock\StockStatus; ?>

<?php /** @var $this \Oander\WarehouseManager\Block\Product\ProductStock */ ?>
<?php /** @var $productStock \Oander\WarehouseManager\Model\ProductStock */ ?>
<?php $productStock = $this->getProductStock(); ?>

<div class="warehouse-info-block warehouse-stock-info">
    <div>
        <?php if($productStock->getStockStatus() == StockStatus::IN_STOCK): ?>
            <span class="stock-status in-stock"><?php /* @escapeNotVerified */ echo __('In Stock') ?></span>
        <?php elseif ($productStock->getStockStatus() == StockStatus::OUT_OF_STOCK) : ?>
            <span class="stock-status out-of-stock"><?php /* @escapeNotVerified */ echo __('Out of Stock') ?></span>
        <?php endif; ?>
    </div>
    <div>
        <?php if($productStock->getAvailability() == Availability::GREEN): ?>
            <span class="stock-status-info"><?php /* @escapeNotVerified */ echo __('Available') ?></span>
        <?php elseif ($productStock->getAvailability() == Availability::RED) : ?>
            <span class="stock-status-info"><?php /* @escapeNotVerified */ echo __('Not available') ?></span>
        <?php elseif ($productStock->getAvailability() == Availability::YELLOW) : ?>
            <span class="stock-status-info"><?php /* @escapeNotVerified */ echo __('Delivery within 3 days') ?></span>
        <?php endif; ?>
    </div>
</div>