<?php
/**
 * Oander_WarehouseManager
 *
 * @author  Tamas Vegvari <tamas.vegvari@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php /** @var $this \Oander\WarehouseManager\Block\Warehouse */ ?>
<div class="warehouse-info text-right">
    <input name="warehouse-stock-list-url" type="hidden" value="<?php echo $this->getAjaxWarehouseStockListUrl() ?>"/>
    <div class="warehouse-close-btn mb-3"><i class="icon icon-close"></i></div>
    <table class="text-left stock-table table table-striped mb-0">
    </table>
</div>

<script type="text/javascript">
    require(['jquery', 'oanderWarehouseView'], function ($, oanderWarehouseView) {
      //
    });
</script>
