<?php
/**
 * Oander_WarehouseManager
 *
 * @author  Tamas Vegvari <tamas.vegvari@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php use Oander\WarehouseManager\Enum\WarehouseBlock; ?>
<?php /** @var $this \Oander\WarehouseManager\Block\Warehouse */ ?>

<div class="warehouse-stock-info"></div>
<div class="warehouse-info-block warehouse-open-btn">
    <input name="stock-sum-url" type="hidden" value="<?php echo $this->getAjaxStockSumUrl() ?>"/>
    <p class="mb-0"><strong><?php /* @escapeNotVerified */ echo __('Where is it in stock?') ?></strong></p>
    <p class="mb-0"><?php /* @escapeNotVerified */ echo __('Find stores where it is in stock') ?></p>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'oanderWarehouseManager',
            'oanderWarehouseView'
        ],
        function(
            $,
            oanderWarehouseManager,
            oanderWarehouseView
        ) {

        var product_id = $('#product_addtocart_form').find('[name="product"]').val();
        oanderWarehouseManager.loadProductSumStockStatus('<?php echo WarehouseBlock::BLOCK_TYPE_VIEW ?>',product_id);
    });
</script>