<!DOCTYPE HTML>
<html lang="">

<head>
    <meta charset="UTF-8">
    <title>iSTYLE | Under maintenance</title>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="iSTYLE, Apple, iPhone, iPad, Mac, Apple Watch">
    <meta name="description" content="iSTYLE - Apple Premium Reseller">
    <meta name="author" content="iSTYLE">
    <meta http-equiv="refresh" content="60">
    <link rel="icon" href="http://www.istyle.eu/skin/frontend/amazingistyle/default/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="all-flex.css">

</head>

<body>





    <!--------------------------------------START------------------------------------------>
    <div class="holdall flex-t-c">


        <!-- SIMPLE BLOCK txt-pic start -->
        <div class="full">

            <div class="wrap flex-c-c">
                <div class="boxx2 coll-8">
                    <div class="img-02"></div>
                </div>
            </div>

            <div class="wrap flex-c-c">
                <div class="boxx coll-8">
                    <div class="tipup">
                        <div class="img-01"></div>
                        <div class="headliner txtcentr">We will be back soon.</div>
                        <div class="subliner txtcentr">Our website is currently being updated.</div>


                        <div class="flex-c-l">
                            <span class="countr-ico">BG</span>
                            <div class="holdmybeer"><span class="parag">В момента онлайн магазина ни се обновява. Скоро ще сме онлайн.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">CZ</span>
                            <div class="holdmybeer"><span class="parag">Currently we are updating our website, but we will be back soon.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">HR</span>
                            <div class="holdmybeer"><span class="parag">Currently we are updating our website, but we will be back soon.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">HU</span>
                            <div class="holdmybeer"><span class="parag">A weboldalt jelenleg frissítjük, hamarosan visszatérünk.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">LV</span>
                            <div class="holdmybeer"><span class="parag">Šobrīd rit mūsu interneta vietnes atjaunināšanas darbi, tā būs pieejama pēc neilga laika.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">MK</span>
                            <div class="holdmybeer"><span class="parag">Моментално ја ажурираме нашата веб страна, се враќаме наскоро.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">RO</span>
                            <div class="holdmybeer"><span class="parag">Currently we are updating our website, but we will be back soon.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">RS</span>
                            <div class="holdmybeer"><span class="parag">Ažuriramo online prodavnicu. Brzo se vraćamo.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">SI</span>
                            <div class="holdmybeer"><span class="parag">Currently we are updating our website, but we will be back soon.</span></div>
                        </div>

                        <div class="flex-c-l">
                            <span class="countr-ico">SK</span>
                            <div class="holdmybeer"><span class="parag">Našu stránku práve aktualizujeme. Za chvíľu sme opäť s vami.</span></div>
                        </div>



                    </div>
                </div>
            </div>
        </div>
        <!-- SIMPLE BLOCK txt-pic end -->


    </div>
    <!--------------------------------------END------------------------------------------>








</body>

</html>
