<?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
<div class="form-group field street required">
    <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
    <div class="control">
        <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getParentBlock()->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="form-control input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>" />
        <div class="nested">
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++) : ?>
                <div class="form-group field additional">
                    <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i + 1 ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i + 1) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getParentBlock()->getStreetLine($_i + 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i + 1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i + 1 ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                    </div>
                </div>
            <?php endfor; ?>
        </div>
    </div>
</div>
