version: 0.0
os: linux
files:
- source: /
  destination: /var/www/istyle.eu/webroot
permissions:
- object: /var/www/istyle.eu/webroot
  pattern: "**"
  owner: www-data
  group: www-data
  mode: 775
  type:
  - directory
- object: /var/www/istyle.eu/webroot
  owner: www-data
  group: www-data
  mode: 664
  type:
  - file
hooks:
  BeforeInstall:
  - location: bin/beforeinstall.sh
    timeout: 180
    runas: root
  AfterInstall:
  - location: bin/install.sh
    timeout: 3600
    runas: root