version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/istyle.mk/webroot
permissions:
  - object: /var/www/istyle.mk/webroot
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/istyle.mk/webroot
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: bin/install.sh
      timeout: 360
      runas: root
