version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/istyle.eu/webroot
permissions:
  - object: /var/www/istyle.eu/webroot
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/istyle.eu/webroot
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
    - location: bin/beforeinstall.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: bin/install.sh
      timeout: 1800
      runas: root
