<?php
/**
 * Oander_FancyFilter
 *
 * @author  David Belicza <david.belicza@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\LayeredNavigation\Block\Navigation */ ?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <a data-html-class="sidebar-opened" data-action="modal-close" class="action close-sidebar hidden-md-up">
            <i class="icon-close-circle"></i>
        </a>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
        <?php if ($filter->getItemsCount()): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                <?php  $wrapOptions = true; endif; ?>
                <div data-role="" class="filter-options-item">
                    <h3 data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></h3>

                    <?php if ($filter->getRequestVar() == 'price'): ?>
                        <div data-role="content" class="filter-options-content">
                            <?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer.price')->render($filter); ?>
                        </div>
                    <?php else: ?>
                        <div data-role="content" class="filter-options-content">
                            <?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>
                        </div>
                    <?php endif; ?>

                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </div>
        <?php else: ?>
            <script>
              require([
                'jquery'
              ], function ($) {
                $('#layered-filter-block').addClass('.filter-no-options');
              });
            </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
