<?php

/**
 * @var \Algolia\AlgoliaSearch\Block\Instant\Hit $block
 */

$priceKey = $block->getPriceKey();
$colors   = $block->getColorKey();

?>

<script type="text/template" id="instant-hit-template">
    <div class="item product product-item">
        <div class="result-wrapper product-item-info" data-container="product-grid">
            <a href="{{url}}" class="product photo product-item-photo">
                <div class="product-item-info" data-container="product-grid">
                    <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                        <div class="product-image-wrapper result-thumbnail">
                            {{#image_url}}<img src="{{{ image_url }}}" />{{/image_url}}
                            {{^image_url}}<span class="no-image"></span>{{/image_url}}
                        </div>
                    </div>
                </div>
            </a>
            <div class="product details product-item-details">
                <a class="product-item-name mb-2" href="{{url}}">
                    {{{ _highlightResult.name.value }}}
                </a>
                <div class="price-box price-final_price" data-role="priceBox" data-product-id="1">
                    <div class="special-price">
                        <span class="price-container price-final_price tax weee">
                            <span class="price-label">Special Price</span>
                            <span id="product-price-1" data-price-type="finalPrice" class="price-wrapper ">
                                <span class="price">{{price<?php echo $priceKey; ?>_formated}}</span>
                            </span>
                        </span>
                    </div>
                    {{#price<?php echo $priceKey; ?>_original_formated}}
                    <div class="old-price">
                        <span class="price-container price-final_price tax weee">
                            <span class="price-label">Regular Price</span>
                            <span id="old-price-1" data-price-type="oldPrice" class="price-wrapper ">
                                <span class="price">{{price<?php echo $priceKey; ?>_original_formated}}</span>
                            </span>
                        </span>
                    </div>
                    {{/price<?php echo $priceKey; ?>_original_formated}}
                </div>
                <div class="swatch-attribute color">
                    <div class="swatch-attribute-options clearfix">
                    {{#color}}
                        <div class="swatch-option color" option-label="{{.}}" style="background: {{.}} no-repeat center; background-size: initial;"></div>
                    {{/color}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>
