<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<section class="block block-dashboard-orders" aria-labelledby="block-title-order">
    <div class="block-dashboard-orders__head">
        <?php $_orders = $block->getOrders(); ?>
        <h2 id="block-title-order" class="h2 block-dashboard-orders__title">
            <strong><?php /* @escapeNotVerified */ echo __('Recent Orders') ?></strong>
        </h2>
        <?php if (sizeof($_orders->getItems()) > 0){ ?>
            <a class="block-dashboard-orders__link text-primary action" href="<?php /* @escapeNotVerified */ echo $block->getUrl('sales/order/history') ?>">
                <span><?php /* @escapeNotVerified */ echo __('View All') ?></span>
                <i class="icon icon-chevron-right"></i>
            </a>
        <?php } ?>
    </div>
    <div class="block-content">
        <?php echo $block->getChildHtml()?>
        <?php if (sizeof($_orders->getItems()) > 0){ ?>
        <div class="block-dashboard-orders-orderlist">
            <?php foreach ($_orders as $_order): ?>
                <div class="block-dashboard-orders-card ui-card">
                    <div class="block-dashboard-orders-card__header">
                        <div class="block-dashboard-orders-card__header-left">
                            <h3 class="h2"><strong><?php echo $block->escapeHtml(__('Order')) ?> : #<?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></strong></h3>
                            <div class="block-dashboard-orders-card__subtitle">
                                <p class="block-dashboard-orders-card__date">
                                    <?php echo $block->escapeHtml(__('Date')) ?>: <?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                                    <span aria-hidden="true" class="d-md-inline d-none">&nbsp; | &nbsp;</span>
                                </p>
                                <p class="block-dashboard-orders-card__status">
                                    <span class="sr-only"><?php echo $block->escapeHtml(__('Status')) ?></span> <strong><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></strong>
                                </p>
                            </div>
                        </div>
                        <div class="block-dashboard-orders-card__header-right">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action outline-primary d-none d-lg-block">
                                <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                            </a>
                        </div>
                    </div>
                    <div class="block-dashboard-orders-card__body">
                         <?php foreach($block->getOrdersItems($_order->getItems()) as $item): ?>
                        <ul class="block-dashboard-orders-card__products">
                            <li>
                                <img src="<?= $block->getProductImageUrl($item->getProduct()) ?>" alt="">
                                <p class="block-dashboard-orders-card__details">
                                    <a href="<?= $item->getProduct()->getProductUrl()?>"><?= $item->getName() ?></a>
                                    <span class="block-dashboard-orders-card__sku"><span class="sr-only">SKU </span><?= $item->getSku() ?></span></p>
                                <p class="block-dashboard-orders-card__price">
                                    <?php
                                    if($item->getData("qty_ordered") != 1)
                                    {
                                        echo (int)$item->getData("qty_ordered")." x";
                                    }
                                    ?>
                                    <?= $_order->formatPrice($item->getPriceInclTax()) ?></p>
                            </li>
                            <?php if($item->getData("childs")) :?>
                            <ul class="block-dashboard-orders-card__sub-products">
                                <?php foreach ($item->getData("childs") as $childItem) :?>
                                <li>
                                    <img src="<?= $block->getProductImageUrl($childItem->getProduct()) ?>" alt="">
                                    <p class="block-dashboard-orders-card__details">
                                        <a href="<?= $childItem->getProduct()->getProductUrl()?>"><?= $childItem->getName() ?></a>
                                        <span class="block-dashboard-orders-card__sku"><span class="sr-only">SKU </span><?= $childItem->getSku() ?></span></p>
                                    <p class="block-dashboard-orders-card__price">
                                        <?php
                                        if($childItem->getData("qty_ordered") != 1)
                                        {
                                            echo (int)$childItem->getData("qty_ordered")." x";
                                        }
                                        ?>
                                        <?= $_order->formatPrice($childItem->getPriceInclTax()) ?></p>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php endif;?>
                        </ul>
                        <?php endforeach; ?>
                    </div>
                    <div class="block-dashboard-orders-card__footer">
                        <p><strong><span class="total"><?php echo $block->escapeHtml(__('Order Total')) ?>:</span> <?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></strong></p>
                        <div class="block-dashboard-orders-card__footer-mobile-link d-xs-block d-lg-none">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action outline-primary">
                                <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php } else{ ?>
        <div class="block-dashboard-orders-no-order">
            <p><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?>
                <a class="text-primary action" href="<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>">
                    <span><?php /* @escapeNotVerified */ echo __('Go to Home Page'); ?></span>
                    <i class="icon icon-chevron-right"></i>
                </a>
            </p>
        </div>
    <?php } ?>
</section>
