<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container clearfix">
  <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
    <div class="loader">
      <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>" style="position: absolute;">
    </div>
  </div>
  <section class="section section--checkout" data-mage-init='{"oanderIstyleCheckout": {}}'>
    <!-- ko foreach: getRegion('authentication') -->
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    <!--/ko-->

    <!-- ko foreach: getRegion('messages') -->
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    <!--/ko-->
    <div class="section__wrapper row">
      <div class="section__content col-12 col-lg-7">
        <div class="block block--product-reservation">
          <div class="block__content-final">
            <h1 class="block__title">
              <?php echo __('Your product has arrived. 🎉'); ?>
            </h1>

            <?php
            echo $this->getLayout()
            ->createBlock("Magento\Cms\Block\Block")
            ->setBlockId("reservation_final_checkout_info")
            ->toHtml();
            ?>

            <?php
            echo $this->getLayout()
            ->createBlock("Oander\SalesforceReservation\Block\Checkout\Dropdown")
            ->setTemplate("Oander_SalesforceReservation::checkout/dropdown.phtml")
            ->toHtml();
            ?>
          </div>

          <div class="block__content-precheckout">
            <?php
            echo $this->getLayout()
            ->createBlock("Magento\Cms\Block\Block")
            ->setBlockId("reservation_precheckout_info")
            ->toHtml();
            ?>
          </div>
        </div>

        <div class="section__progressbar">
          <!-- ko foreach: getRegion('progressBar') -->
          <!-- ko template: getTemplate() -->
          <!-- /ko -->
          <!--/ko-->
        </div>

        <!-- ko foreach: getRegion('steps') -->
        <!-- ko template: getTemplate() -->
        <!-- /ko -->
        <!--/ko-->
      </div>

      <div class="section__aside col-12 col-lg-4 offset-lg-1">
        <!-- ko foreach: getRegion('sidebar') -->
        <!-- ko template: getTemplate() -->
        <!-- /ko -->
        <!--/ko-->
      </div>
    </div>
  </section>
  <script type="text/x-magento-init">
    {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
            }
        }
    </script>
  <script>
    window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
    // Create aliases for customer.js model from customer module
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
  </script>
  <script type="text/javascript">
    require([
      'oander.checkout.info.dialog'
    ]);
  </script>
  <script>
    require([
      'mage/url',
      'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
      blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
      return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl(); ?>');
    })
  </script>
</div>
