<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = ''; ?>
<?php if ($block->isLoggedIn()) : ?>
    <?php $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams()) ?>
    <li><a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo $block->escapeHtml(__('My Account')); ?></a></li>
<?php endif ?>

<li class="authorization-link" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
    <a <?php /* @escapeNotVerified */ echo $block->getLinkAttributes(); ?><?php /* @escapeNotVerified */ echo $dataPostParam; ?>>
        <?php echo $block->escapeHtml($block->getLabel()); ?>
    </a>
</li>