<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct()
?>
<?php if ($_additional = $block->getAdditionalData()): ?>

    <?php // echo count($_additional)?>

    <div class="additional-attributes-wrapper">
        <div class="row">
            <?php foreach ($_additional as $_data): ?>
                <div class="col-sm-6 col-item">
                    <div class="mb-0 label"><strong><?php echo $block->escapeHtml(__($_data['label'])) ?></strong></div>
                    <div class="mb-4 data"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

<?php endif;?>
