<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Oander\IstyleCheckout\Block\Checkout\Success\Registration */
// @codingStandardsIgnoreFile
?>
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <?= $block->getChildHtml('loyalty_registration_marekting'); ?>
        <form
            id="registration"
            class="checkout-success-registration"
            data-bind="scope:'registration'"
        >
            <div
                class="form-group field password required"
                data-bind="mageInit: {'passwordStrengthIndicator': {}}"
            >
                <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                <div class="control">
                    <div class="password-eye-holder">
                        <input
                            type="password"
                            name="password"
                            id="password"
                            title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                            placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                            class="form-control input-text input-password-eye"
                            data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                            data-validate="{required:true, 'validate-customer-password':true}"
                            autocomplete="off"
                        >
                        <span class="password-eye-icon"></span>
                        <script type="text/javascript">
                            var icon = document.querySelector('.password-eye-icon'),
                                input = document.getElementById('password');

                            icon.addEventListener('click', function (event) {
                                icon.classList.toggle('show');
                                if (input.type === 'password') {
                                    input.type = 'text';
                                } else {
                                    input.type = 'password';
                                }
                            });
                        </script>
                    </div>
                    <div id="password-strength-meter-container" data-role="password-strength-meter" >
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <?php echo $block->getChildHtml('register_agreements'); ?>
            </div>


            <!-- ko template: getTemplate() --><!-- /ko -->
            <script type="text/x-magento-init">
                {
                    "#registration": {
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "registration": {
                                    "component": "Oander_IstyleCheckout/js/view/registration",
                                    "config": {
                                        "registrationUrl": "<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl(); ?>",
                                        "email": "<?php /* @escapeNotVerified */ echo $block->getEmailAddress(); ?>",
                                        "isRecaptchaEnabled": "<?= /* @escapeNotVerified */ $block->isRecaptchaEnabled() ?>",
                                        "invisibleKey": "<?= /* @escapeNotVerified */ $block->getInvisibleKey() ?>",
                                        "language": "<?= /* @escapeNotVerified */ $block->getLanguageCode() ?>",
                                        "position": "<?= /* @escapeNotVerified */ $block->getPositionFrontend() ?>",
                                        "theme": "<?= /* @escapeNotVerified */ $block->getThemeFrontend() ?>",
                                        "generalErrorMessage": "<?= /* @escapeNotVerified */ __('Server error during registration.') ?>"
                                    },
                                    "children": {
                                        "errors": {
                                            "component": "Magento_Ui/js/view/messages",
                                            "sortOrder": 0,
                                            "displayArea": "messages",
                                            "config": {
                                                "autoHideTimeOut": -1
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            </script>
        </form>
        <div class="reg-messages messages">
            <div class="message"></div>
        </div>
    </div>
</div>
