<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
?>
<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildrenItems()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <li class="profile-order-card__products-bundle-title">
                <div class="col label"><?php /* @escapeNotVerified */ echo $attributes['option_label'] ?></div>
            </li>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <li id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" class="<?php if ($_item->getParentItem()): ?>profile-order-card__products-bundle<?php else: ?>profile-order-card__products-bundle-parent<?php endif; ?>"<?php if ($_item->getParentItem()): ?><?php endif; ?>>
        <?php if(!$_item->getParentItem()):?>
            <img src="<?= $block->getProductImageUrl($_item->getProduct())?>" alt="">
        <?php endif;?>
        <p class="profile-order-card__details">
            <?php if (!$_item->getParentItem()): ?>
                <span class="sr-only"><?php echo $block->escapeHtml(__('Product Name')); ?></span>
                <span class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></span>
            <?php else: ?>
                <span class="sr-only"><?php echo $block->escapeHtml(__('Price')); ?></span>
                <span><?php echo $block->getValueHtml($_item)?></span>
            <?php endif; ?>
            <span class="profile-order-card__sku">
                <span class="sr-only"><?php echo $block->escapeHtml(__('SKU')); ?> </span><?php /* @escapeNotVerified */ echo $block->prepareSku($_item->getSku()) ?>
            </span>
        </p>
        <ul class="profile-order-card__qty" aria-label="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <?php if (
            ($_item->getParentItem() && $block->isChildCalculated()) ||
            (!$_item->getParentItem() && !$block->isChildCalculated()) || ($_item->getQtyShipped() > 0 && $_item->getParentItem() && $block->isShipmentSeparately())):?>
                <?php endif; ?>
                <?php if (($_item->getParentItem() && $block->isChildCalculated()) ||
                    (!$_item->getParentItem() && !$block->isChildCalculated())): ?>
                    <?php if ($_item->getQtyOrdered() > 0): ?>
                        <li class="item">
                            <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered'); ?></span>
                            <span class="content">&nbsp;<?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1 ?></span>
                        </li>
                    <?php endif; ?>
                    <?php if ($_item->getQtyShipped() > 0 && !$block->isShipmentSeparately()): ?>
                        <li class="item">
                            <span class="title"><?php /* @escapeNotVerified */ echo __('Shipped'); ?></span>
                            <span class="content">&nbsp;<?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1 ?></span>
                        </li>
                    <?php endif; ?>
                    <?php if ($_item->getQtyCanceled() > 0): ?>
                        <li class="item">
                            <span class="title"><?php /* @escapeNotVerified */ echo __('Canceled'); ?></span>
                            <span class="content">&nbsp;<?php /* @escapeNotVerified */ echo $_item->getQtyCanceled()*1 ?></span>
                        </li>
                    <?php endif; ?>
                    <?php if ($_item->getQtyRefunded() > 0): ?>
                        <li class="item">
                            <span class="title"><?php /* @escapeNotVerified */ echo __('Refunded'); ?></span>
                            <span class="content">&nbsp;<?php /* @escapeNotVerified */ echo $_item->getQtyRefunded()*1 ?></span>
                        </li>
                    <?php endif; ?>
                <?php elseif ($_item->getQtyShipped() > 0 && $_item->getParentItem() && $block->isShipmentSeparately()): ?>
                    <li class="item">
                        <span class="title"><?php /* @escapeNotVerified */ echo __('Shipped'); ?></span>
                        <span class="content">&nbsp;<?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1 ?></span>
                    </li>
                <?php endif; ?>
                <?php if (
                ($_item->getParentItem() && $block->isChildCalculated()) ||
                (!$_item->getParentItem() && !$block->isChildCalculated()) || ($_item->getQtyShipped() > 0 && $_item->getParentItem() && $block->isShipmentSeparately())):?>
            <?php endif; ?>
        </ul>
            <?php if (!$_item->getParentItem()): ?>
            <p class="profile-order-card__price">
                <span>
                    <span class="sr-only"><?php echo $block->escapeHtml(__('Subtotal')); ?></span>
                    <?php echo $block->getItemPriceHtml(); ?>
                </span>
            </p>
            <?php endif; ?>
    </li>
<?php endforeach; ?>

<?php if ($_showlastRow && (($_options = $block->getItemOptions()) || $block->escapeHtml($_item->getDescription()))): ?>
    <div>
        <div class="col options" colspan="5">
            <?php if ($_options = $block->getItemOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                            <dd><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </div>
    </div>
<?php endif; ?>
