<div class="price-box" data-role="priceBox">
    <div class="regular-price" id="final-price">
        <span class="price-container price-final_price">
            <span data-price-type="finalPrice" class="price-wrapper">
                <span class="price"></span>
            </span>
        </span>
    </div>
    <div class="old-price" id="old-price" style="display: none;">
        <span class="price-container price-final_price">
            <span data-price-type="oldPrice" class="price-wrapper ">
                <span class="price"></span>
            </span>
        </span>
    </div>
</div>
