<?php
$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?php echo $block->escapeHtml($fieldCssClass); ?>">
    <label class="label" for="<?php echo $block->escapeHtml($block->getHtmlId())?>"><span><?php echo $block->escapeHtml($block->getLabel()) ?></span></label>
    <div class="control customer-dob">
        <?php echo $block->getFieldHtml(); ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?php echo $block->escapeHtml($_message); ?></div>
        <?php endif; ?>
    </div>
</div>
