<?php
/**
 * Oander_WonderWidget
 *
 * @author  David Belicza <david.belicza@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php /** @var $this \Oander\WonderWidget\Block\Video */?>

<div class="widget-block block oander-wonder-widget-video">
    <div class="content">
        <?php if ($this->getImage()): ?>
            <div class="image-wrapper" style="background-image: url('<?php echo $this->getImage(); ?>')">
                <a
                <?php if ($this->getVideoType() == 'youtube'): ?>
                    href="https://www.youtube.com/watch?v=<?php echo $this->getVideoId(); ?>"
                <?php elseif ($this->getVideoType() == 'vimeo'): ?>
                    href="https://vimeo.com/<?php echo $this->getVideoId(); ?>"
                <?php endif; ?>
                   data-action="open-wonder-video" class="wonder-widget-video-link">
                    <img src="<?php echo $this->getImage(); ?>" />
                </a>
                <div class="content-block">
                    <i class="icon icon-play"></i>
                    <?php if ($this->getTitle()): ?>
                        <div class="title"><p><?php echo $this->getTitle(); ?></p></div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
