<div class="footer_pedagogique">
    <p>Sistema de amortización francés con cuotas constantes. Intereses de la financiación 0€. El primer pago se abona
        en el momento de la compra. El resto de los pagos se realizan de forma mensual, por lo que el plazo de la
        financiación irá desde el mínimo de 2 meses (3 pagos) hasta un máximo de 11 meses (12 pagos), dependiendo de la
        oferta comercial vigente. Pago aplazado ofrecido y sujeto a la aprobación de Oney Servicios Financieros. Válido
        para tarjetas de débito o crédito VISA o MASTERCARD con una fecha de validez superior al plazo de la
        financiación. <a href="https://www.oney.es/aviso-legal/informacion-legal-3x4xoney"
                         target="_blank">Información legal de 3x 4x Oney </a></p>
</div>
