<?php
/** @var \Algolia\AlgoliaSearch\Block\Algolia $block */

$config = $block->getConfigHelper();

$catalogSearchHelper = $block->getCatalogSearchHelper();

$placeholder = __('Search for products, categories, ...');

/** Render form with autocomplete input **/
if ($config->isDefaultSelector()): ?>
<div class="header-right-block header-search" id="header-search">
    <div class="block block-toggle hidden-md-down">
        <a href="#" class="action showsearch skip-link" id="showsearch">
            <i class="icon icon-search default-state"></i>
            <i class="icon icon-close opened-state"></i>
        </a>
    </div>
    <div class="block block-content header-search-content" style="display: none"
         data-mage-init='{"dropdownDialog":{
                "triggerTarget":"#showsearch",
                "appendTo":"#header-search",
                "timeout": "0",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
        <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
            <div id="algolia-searchbox">
                <label for="search"><?php echo __('Search:') ?></label>
                <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" class="input-text form-control algolia-search-input" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" placeholder="<?php echo $placeholder; ?>" />
                <span class="clear-cross clear-query-autocomplete"></span>
                <span id="algolia-glass" class="magnifying-glass" width="24" height="24"></span>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>