<?php
/**
 * Oander_ImportM2
 *
 * @author  Tamas Vegvari <tamas.vegvari@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */

?>
<?php /** @var \Oander\ImportM2\Block\Adminhtml\System\Config\Form\Field\StartImportCategory $this */ ?>
<button type="button" style="display: none"
        class="action-default scalable primary ui-button ui-state-default ui-button-text-only"
        onclick="location.href = '<?php echo $this->getStartUrl(); ?>';">
    <span class="ui-button-text" >
        <span>
            <?php echo __('DO NOT PUSH! 3'); ?>
        </span>
    </span>
</button>
