<?php /** @var $block \Oander\AppleServices\Block\AppleTv */ ?>

<form method="post"
      class="apple-music-widget"
      style="min-height: 250px; margin-top: 150px; text-align: center;">
    <button type="submit"
            id="apple-music-request"
            class="action outline-dark"
            style="margin-bottom: 16px"><?php echo $block->getRequestButtonLabel(); ?></button>
    <a href="#" id="apple-music-redeem"
       style="display: none; margin-bottom: 16px"
       class="action dark"
       target="_blank"><?php echo $block->getRedeemButtonLabel(); ?></a>
    <?php if ($block->getCodeDescription()): ?>
        <p id="apple-music-description"
           class="code-description"
           style="display: none;">
            <?php echo $block->getCodeDescription(); ?>
        </p>
    <?php endif; ?>
    <p id="apple-musice-code" style="display: none"></p>
    <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
    <input type="hidden" name="action" value="validate_captcha">
</form>

<?php $siteKey = $block->getCaptchaKey(); ?>
<?php  //FE ezt az url hívjuk meg?>
<?php $ajaxUrl = $block->getUrl("appleservices/endpoint/ajaxcall"); ?>
<?php  //FE küldi át ezeket is?>
<?php $apiEndpoint = $block->getApiEndpoint(); ?>
<?php $uniqueID = $block->getUniqueId(); ?>
<?php $secretKey = $block->getSecretKey(); ?>
<?php $referalToken = $block->getReferralToken(); ?>

<?php
//Ezeket neveket használd! : unique_id,api_endpoint,secret_key,captcha
?>
<script src="https://www.google.com/recaptcha/api.js?onload=ReCaptchaCallbackV3&render=<?php echo $siteKey ?>"></script>
<script>
    var ReCaptchaCallbackV3 = function() {
        require([
            'jquery'
        ], function ($) {
            grecaptcha.ready(function () {
                grecaptcha.execute('<?php echo $siteKey ?>', { action: 'validate_captcha' }).then(function (token) {
                    document.getElementById('g_recaptcha_response').value = token;

                    var btnRequest = $('#apple-music-request');
                    var btnRedeem = $('#apple-music-redeem');
                    var code = $('#apple-musice-code');
                    var desc = $('#apple-music-description');
                    var storage = JSON.parse(localStorage.getItem('apple-music'));
                    var url = window.location.origin + '/applemusic.php';
                    // var url = 'https://dev.istyle.hu/applemusic.php';
                    var expire_time = new Date(new Date().getTime() + '<?php echo $block->getCookieLifetime(); ?>' * 60000).valueOf();

                    if (storage != null && storage.isRetrieved && storage.expire_time > new Date().valueOf()) {
                        btnRequest.hide();
                        btnRedeem.show().attr('href', storage.url);
                        desc.show();
                        code.show().text(storage.code);
                    } else {
                        $(btnRequest).on('click', function (e) {
                            e.preventDefault();

                            $.ajax({
                                showLoader: true,
                                url: url,
                                type: 'POST',
                                cache: false,
                                data: {
                                    captcha: token//grecaptcha.getResponse()
                                }
                            }).done(function (getData) {
                                var data = JSON.parse(getData);
                                if(data["error"] != null)
                                    alert(data["message"]);
                                else {
                                    if (storage != null) {
                                        localStorage.removeItem('apple-music');
                                    }

                                    localStorage.setItem(
                                        'apple-music',
                                        JSON.stringify({
                                            isRetrieved: true,
                                            url: data.redemption_url,
                                            code: data.code,
                                            expire_time: expire_time
                                        })
                                    )

                                    btnRequest.hide();
                                    btnRedeem.show().attr('href', data.redemption_url);
                                    desc.show();
                                    code.show().text(data.code);
                                }
                            });
                        });
                    }

                });
            });
        })
    };
</script>
