<?php if($block->getParentBlock()->getReplacePostcodeRegion() && $block->getParentBlock()->getRegionCollection()) : ?>
    <div class="form-group field ro-city select2 required">
        <div class="control">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <select name="city" style="width: 100%" id="city" class="form-control ro-city-select required-entry <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>">
            </select>
        </div>
    </div>
    <script>
        require(["roRegionCity"], function($) {
        });
    </script>
<?php else : ?>
    <div class="form-group field city required">
        <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
        <div class="control">
            <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getParentBlock()->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
        </div>
    </div>
<?php endif; ?>
