<?php
    $isCompany = $block->getParentBlock()->getAddress()->getCustomAttribute('is_company')?$block->getParentBlock()->getAddress()->getCustomAttribute('is_company')->getValue():"0";
?>
<style>
    input.tgl-radio-tab-child {
        position: absolute;
        left: -99999em;
        top: -99999em;
        opacity: 1;
        z-index: 1;
    }

    input.tgl-radio-tab-child+label {
        cursor: pointer;
        float: left;
        border: 1px solid #aaa;
        margin-right: -1px;
        padding: .5em 1em;
        position: relative;
    }

    input.tgl-radio-tab-child+label:hover {
        background-color: #eee;
    }

    [type=radio]:checked+label {
        background-color: #c30;
        z-index: 1;
    }
</style>
<label for="abc">ABC<span style="color: red;">*</span></label>
<div class="form-check">
    <input type="hidden" id="is_company" name="is_company" value="<?php echo $isCompany?>" />
    <div class="tgl-radio-tabs">
        <input id="is_company_radio_individual" type="radio" class="form-check-input tgl-radio-tab-child" name="is_company_radio" <?php echo $isCompany?"":"checked"?> onclick="document.getElementById('is_company').value=this.value;"><label for="x" class="radio-inline">ABCDEFGHIJKL</label>
        <input id="is_company_radio_company" type="radio" class="form-check-input tgl-radio-tab-child" name="is_company_radio" <?php echo $isCompany?"checked":""?> onclick="document.getElementById('is_company').value=this.value;"><label for="y" class="radio-inline">MNOPQRSTUVWXYZ</label>
    </div>
</div>