<!--TODO BE: if-elni az egészet CZ, RS és SK store-okra-->
<div class="form-group field pfpj_reg_no registration-number required">
    <label class="label" for="pfpj_reg_no"><span><?php /* @escapeNotVerified */ echo __('Registration Number') ?></span></label>
    <div class="control">
<!--        TODO BE: value: --><?php //echo $block->escapeHtml($block->getParentBlock()->getAddress()->getRegNo()) ?>
        <input type="text" name="pfpj_reg_no" id="pfpj_reg_no" title="<?php /* @escapeNotVerified */ echo __('Registration Number') ?>" value="" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('pfpj_reg_no') ?>">
    </div>
</div>
