<div class="form-group field region required" style="display: none;">
    <label class="label" for="region"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
    <div class="control">
        <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getParentBlock()->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="form-control input-text required-entry" />
    </div>
</div>
<script>
  require(["jquery"], function($) {
    var removeDisabled = setInterval(function() {
      if ($('input[name="region"][disabled="disabled"]').length) {
        $('input[name="region"]').removeAttr('disabled');
        clearInterval(removeDisabled);
      }
    }, 100);
  });
</script>
