<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $url = $block->getUrl('adatvedelmi-szabalyzat'); ?>
<div class="block block-newsletter js-accordion-box" id="oander-newsletter">
    <h2 class="footer-block-title"><?php /* @escapeNotVerified */ echo __('Subscribe to Newsletter') ?></h2>

    <?php

        echo $block->getLayout()
            ->createBlock(\Magento\Cms\Block\Block::class)
            ->setBlockId('mail_chimp_footer')
            ->toHtml();
    ?>

</div>
