<!-- Page -->
<div class="content-accessories">
    <div class="columns row mb-3">
        <div class="column main col-md-8 col-lg-9 flex-md-last order-md-last">
            <div class="row">
                <div class="col-sm-6 hidden-sm-down">
                    <div class="product-box">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 hidden-sm-down">
                <div class="product-box">
                    <div class="description">
                        <h2 class="title">Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p><span class="price">49 999 Ft</span></p>
                        <a href="#" class="btn btn-red">Learn More</a>
                    </div>
                    <div class="media">
                        <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                    </div>
                </div>
            </div>
            </div>
            <div class="row">
                <div class="col-sm-12 hidden-sm-down">
                    <div class="product-box full-size">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-4.png" alt=""></div>
                    </div>
                </div>
            </div>
            <div class="slider-container">
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html" class="product photo product-item-photo" tabindex="-1">
                            <div class="product-image-container oander-category-badge-image-container" style="width:400px;">
                                <span class="badge-container badge- badge-item-1">
                                    <span class="badge-box">
                                       <span class="badge-label">- 17 %</span>
                                    </span>
                                </span>
                                <div class="product-image-wrapper">
                                    <img class="product-image-photo" src="http://istyle/pub/media/catalog/product/cache/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/b/e/beats1.jpg" width="400" height="400" alt="Beats by Dr. Dre - EP fejhallgató">
                                </div>
                            </div>
                        </a>
                        <div class="product details product-item-details">
                            <a class="product-item-name mb-2" href="http://istyle/beats-by-dr-dre-ep-fejhallgato.html">
                                Beats by Dr. Dre - EP fejhallgató                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem, eum facere in molestias numquam optio, quaerat quas reprehenderit unde velit voluptatibus?</p>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047">
                                <div class="old-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Regular Price</span>
                                        <span id="old-price-2047" data-price-amount="31900" data-price-type="oldPrice" class="price-wrapper ">
                                            <span class="price">31 900 Ft</span>
                                        </span>
                                    </span>
                                </div>
                                <div class="special-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-2047" data-price-amount="26500" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">26 500 Ft</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 hidden-sm-down">
                    <div class="product-box">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 hidden-sm-down">
                    <div class="product-box">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 hidden-sm-down">
                    <div class="product-box full-size">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-4.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sidebar-wrapper col-md-4 col-lg-3">
            <div class="sidebar-background">
                <div class="sidebar sidebar-main"></div>
                <div class="sidebar sidebar-additional">
                    <div class="block filter-options">
                        <div class="block-title"><h2>Block Title #1</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                        <hr>
                        <div class="block-title"><h2>Block Title #2</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                        <hr>
                        <div class="block-title"><h2>Block Title #3</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Slick init -->
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(function () {
            $('.content-accessories .slider-container').slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 2,
                slidesToScroll: 2,
                mobileFirst: true,
                responsive: [
                    {
                        breakpoint: 992,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3
                        }
                    }
                ]
            });
        });
    });
</script>
