<!-- Slick init -->
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(function () {
            $(".content-accessories .slider-container").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 3,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
    });
</script>
<!-- Page -->
<div class="content-accessories">
    <div class="columns row mb-3">
        <div class="column main col-md-8 col-lg-9 flex-md-last order-md-last">
            <div class="row">
                <div class="col-sm-6 hidden-sm-down">
                    <div class="product-box">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 hidden-sm-down">
                <div class="product-box">
                    <div class="description">
                        <h2 class="title">Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p><span class="price">49 999 Ft</span></p>
                        <a href="#" class="btn btn-red">Learn More</a>
                    </div>
                    <div class="media">
                        <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                    </div>
                </div>
            </div>
            </div>
            <div class="row">
                <div class="col-sm-12 hidden-sm-down">
                    <div class="product-box full-size">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-4.png" alt=""></div>
                    </div>
                </div>
            </div>
            <div class="slider-container">
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
                <div><a href="#"><img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt=""></a></div>
            </div>
            <div class="row">
                <div class="col-sm-6 hidden-sm-down">
                    <div class="product-box">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 hidden-sm-down">
                    <div class="product-box">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-2.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 hidden-sm-down">
                    <div class="product-box full-size">
                        <div class="description">
                            <h2 class="title">Lorem Ipsum</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <p><span class="price">49 999 Ft</span></p>
                            <a href="#" class="btn btn-red">Learn More</a>
                        </div>
                        <div class="media">
                            <img src="http://istyle/pub/media/wysiwyg/sample-img-4.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sidebar-wrapper col-md-4 col-lg-3">
            <div class="sidebar-background">
                <div class="sidebar sidebar-main"></div>
                <div class="sidebar sidebar-additional">
                    <div class="block filter-options">
                        <div class="block-title"><h2>Block Title #1</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                        <hr>
                        <div class="block-title"><h2>Block Title #2</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                        <hr>
                        <div class="block-title"><h2>Block Title #3</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
