<div class="content-accessories">
    <div class="columns row mb-3">
        <div class="column main col-md-8 col-lg-9 flex-md-last order-md-last">
            <h1>Main</h1>
        </div>
        <div class="sidebar-wrapper col-md-4 col-lg-3">
            <div class="sidebar-background">
                <div class="sidebar sidebar-main"></div>
                <div class="sidebar sidebar-additional">
                    <div class="block filter-options">
                        <div class="block-title"><h2>Block Title #1</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                        <hr>
                        <div class="block-title"><h2>Block Title #2</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                        <hr>
                        <div class="block-title"><h2>Block Title #3</h2></div>
                        <div class="block-content">
                            <div class="filter-options-content">
                                <ol class="items">
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                    <li class="item"><a href="#">Item</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
