<?php
/**
 * Oander_CustomerFileUpload
 *
 * @author  Gabor Kuti <gabor.kuti@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */ ?>

<?php /** @var $block \Oander\CustomerFileUpload\Block\Customer\FileUpload */ ?>
<?php $files = $block->getFiles() ?>
<?php if (count($files)): ?>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped table--files">
                <thead>
                    <tr>
                        <th><?php echo __('File') ?> #</th>
                        <th><?php echo __('Date') ?></th>
                        <th><?php echo __('File') ?></th>
                        <th><?php echo __('Action') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php $counter = 1 ?>
                <?php foreach ($files as $file): ?>
                    <?php /** @var $file \Oander\CustomerFileUpload\Model\File */ ?>
                    <tr>
                        <td data-th="<?php echo __('File') ?> #"><?php echo $counter++ ?></td>
                        <td data-th="<?php echo __('Date') ?>"><?php echo $file->getCreatedAt() ?></td>
                        <td data-th="<?php echo __('File') ?>"><a href="<?php echo $block->getDownloadUrl($file) ?>"><?php echo $file->getFileName() ?></a></td>
                        <td data-th="<?php echo __('Action') ?>">
                            <a href="<?php echo $block->getDeleteUrl($file) ?>"
                               onclick="return confirm('<?php echo __('Are you sure') ?>')">
                                <?php echo __('Delete') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif ?>
<div class="row">
    <div class="col-12">
        <h3 class="block-title"><?php echo __('Add new file') ?></h3>
    </div>
    <div class="col-12">
        <form class="row customer-file-upload-form"
              method="post"
              id="customer-file-upload-form"
              action="<?php echo $block->getUploadUrl() ?>"
              enctype="multipart/form-data">
            <div class="col-12 col-lg-8 form-group">
                <label class="custom-file">
                    <input type="file" class="custom-file-input"
                           name="<?php echo $block->getFileParam() ?>" id="<?php echo $block->getFileParam() ?>" />
                    <span class="custom-file-control control-data" data-input-text="<?php echo __('File') ?>"
                          data-button-text="<?php echo __('Browse') ?>"></span>
                </label>
                <span class="filename"><?php echo __('Nothing selected') ?></span>
            </div>
            <div class="col-12 col-lg-4 form-group">
                <input class="action save primary" type="submit" value="<?php echo __('Save') ?>"/>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
  require([
    'oander.file-upload'
  ]);
</script>
