<?php
/**
 * Oander_WarehouseManager
 *
 * @author  Tamas Vegvari <tamas.vegvari@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php use Oander\WarehouseManager\Enum\ProductStock\Availability; ?>
<?php use Oander\WarehouseManager\Enum\ProductStock\StockStatus; ?>

<?php /** @var $this \Oander\WarehouseManager\Block\Product\ProductStock */ ?>
<?php /** @var $productStock \Oander\WarehouseManager\Model\ProductStock */ ?>
<?php $productStock = $this->getProductStock(); ?>
<?php $isDefaultSelections = $productStock->getData('default_selections') ?>

<div class="warehouse-info-block warehouse-stock-info">
    <div class="block-icon">
        <?php if (!$isDefaultSelections) : ?>
            <i class="icon icon-out-of-stock"></i>
        <?php elseif ($productStock->getStockStatus() == StockStatus::IN_STOCK) : ?>
            <i class="icon icon-box-check"></i>
        <?php elseif ($productStock->getStockStatus() == StockStatus::OUT_OF_STOCK) : ?>
            <i class="icon icon-out-of-stock"></i>
        <?php endif; ?>
    </div>

    <div class="stock-status-wrapper">
        <?php if (!$isDefaultSelections) : ?>
            <span class="stock-status external-stock"><?php /* @escapeNotVerified */ echo __('Custom Configuration') ?></span>
        <?php elseif ($productStock->getStockStatus() == StockStatus::IN_STOCK) : ?>
            <span class="stock-status in-stock"><?php /* @escapeNotVerified */ echo __('In Stock') ?></span>
        <?php else : ?>
            <span class="stock-status out-of-stock"><?php /* @escapeNotVerified */ echo __('Out of Stock') ?></span>
        <?php endif; ?>
    </div>

    <div class="stock-status-info mb-2">
        <?php if (!$isDefaultSelections): ?>
            <?php /* @escapeNotVerified */ echo __('Delivery within 3-5 weeks') ?>
        <?php elseif ($productStock->getAvailability() == Availability::GREEN): ?>
            <?php /* @escapeNotVerified */ echo __('Available') ?>
        <?php elseif ($productStock->getAvailability() == Availability::RED) : ?>
            <?php /* @escapeNotVerified */ echo __('Not available') ?>
        <?php elseif ($productStock->getAvailability() == Availability::YELLOW) : ?>
            <?php /* @escapeNotVerified */ echo __('Delivery within 3 days') ?>
        <?php endif; ?>
    </div>
    <?php if ($productStock->getAvailability() != Availability::RED) : ?>
    <div class="block-details-link stock-link"><?php /* @escapeNotVerified */ echo __('Where is it in stock?') ?></div>
    <?php endif; ?>
</div>
