<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td class="col image" data-th="<?php echo $block->escapeHtml(__('Product-image')); ?>">
        <?php if ($block->hasProductUrl()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
           title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else:?>
            <span class="product-item-photo">
            <?php endif;?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()):?>
        </a>
        <?php else: ?>
        </span>
        <?php endif; ?>
    </td>
    <td class="col item" data-th="<?php echo $block->escapeHtml(__('Item')); ?>">
        <div class="product-item-details">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
            <?php else: ?>
                <?php echo $block->escapeHtml($block->getProductName()) ?>
            <?php endif; ?>

            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>

            <div class="sku"><?php echo $product->getSku(); ?></div>
        </div>
    </td>

    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="form-group field qty">
            <label class="label sr-only" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
            </label>
            <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                   name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                   data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                   value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                   type="number"
                   size="4"
                   title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                   class="form-control input-text qty"
                   maxlength="12"
                   data-validate="{required:true,'validate-greater-than-zero':true}"
                   min="1"
                   data-role="cart-item-qty"/>
        </div>
    </td>

    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
    </td>

    <td class="col delete" data-th="<?php echo $block->escapeHtml(__('Delete'));?>">
        <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
    </td>
</tr>
</tbody>
