<?php
/** @var $block \Oander\CartButton\Block\Ajax\Button */

//Get Object Manager Instance
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->create('Magento\Catalog\Helper\Data');
?>
<div id="addcartbutton-apple-pay"></div>
<div id="addcartbutton-original">
    <button form="product_addtocart_form" id="product-addtocart-button"
            class="btn btn-primary action tocart oander-product-addtocart-button js-oander-product-addtocart-button"
            value="<?php echo $helper->getTaxPrice($block->getProduct(), $block->getProduct()->getFinalPrice(), true) ?>">
        <?php /* @escapeNotVerified */ echo __('Add to Cart'); ?>
        <img class="oander-product-addtocart-button-loader"
             src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('svg/loader-white.svg'); ?>"
             alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>">
    </button>
</div>
<script type="text/javascript">
    require(["jquery",'Oander_ApplePay/js/button'], function ($,button) {
        var selectors = {
            minicart: '[data-block="minicart"]',
            checkoutbutton: '#top-cart-btn-checkout',
            applepayObject: '#applepay-object'
        };

        $(document).on('applePayTrigger', function() {
            changebutton();
        });

        if(window.applePay!=='undefined')
            if(window.applePay.init!=='undefined')
                changebutton();

        function changebutton() {
            var applePay = $(selectors.applepayObject).data('mageApplepay');
            if(applePay.canUseApplePay()) {
                button.init(document.getElementById('addcartbutton-apple-pay'),applePay);
            }
        };
    });
</script>
