<?php
/** @var $block \Oander\CartButton\Block\Ajax\Button */

//Get Object Manager Instance
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->create('Magento\Catalog\Helper\Data');
?>
<div id="addcartbutton-apple-pay" data-productid="<?php echo $block->getProduct()->getId() ?>"></div>
<div id="addcartbutton-original">
    <button form="product_addtocart_form" id="product-addtocart-button"
            class="btn btn-primary action tocart oander-product-addtocart-button js-oander-product-addtocart-button"
            value="<?php echo $helper->getTaxPrice($block->getProduct(), $block->getProduct()->getFinalPrice(), true) ?>">
        <?php /* @escapeNotVerified */ echo __('Add to Cart'); ?>
        <img class="oander-product-addtocart-button-loader"
             src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('svg/loader-white.svg'); ?>"
             alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>">
    </button>
</div>
<script type="text/javascript">
    require(["jquery", 'applePay', 'domReady!'], function ($) {
        var selectors = {
            applepayObject: 'applepay-object'
        };

        if (document.getElementById('addcartbutton-apple-pay').innerHTML === '') {
            var applePayObject = document.getElementById(selectors.applepayObject);
            var applePay = $(applePayObject).data('mageApplepay');
            if(typeof applePay !== 'undefined') {
                addProductApplePayButton();
            }
            else {
                applePayObject.addEventListener("init", function() {addProductApplePayButton()});
            }
        }

        function addProductApplePayButton() {
            var applePayObject = document.getElementById(selectors.applepayObject);
            var applePay = $(applePayObject).data('mageApplepay');
            if (applePay.canUseApplePay('<?php echo \Oander\ApplePay\Enum\DisplayIn::PRODUCTPAGE; ?>')) {
                applePay.addProductCartButton(document.getElementById('addcartbutton-apple-pay'));
            }
        }
    });
</script>
