<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block block--discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "active": 1, "saveState": false}}'>
  <div class="block__content" data-role="content">
    <form id="discount-coupon-form" action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/couponPost') ?>" method="post" data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                            "removeCouponSelector": "#remove-coupon",
                            "applyButton": "button.action.apply",
                            "cancelButton": "button.action.cancel"}}'>
      <div class="fieldset coupon<?php strlen($block->getCouponCode()) ? ' applied' : '' ?>">
        <input type="hidden" name="remove" id="remove-coupon" value="0" />

        <?php if (!strlen($block->getCouponCode())) : ?>
          <div class="block block--new-coupon">
            <div class="block__title">
              <?php echo __('Add coupon code'); ?>
            </div>
            <div class="block__input-group">
              <input type="text" class="block__input input-text form-control input-discount" id="coupon_code" name="coupon_code" placeholder="<?php echo $block->escapeHtml(__('Add coupon code')); ?>" autofocus />
              <span class="input-group-btn">
                <button class="block__action action apply primary" type="button" value="<?php /* @escapeNotVerified */ echo __('Apply') ?>">
                  <span><?php /* @escapeNotVerified */ echo __('Apply') ?></span>
                </button>
              </span>
            </div>
          </div>
        <?php else : ?>
          <div class="block block--remove-coupon">
            <div class="block__table">
              <div class="block__mark">
                <?php echo __('Coupon discount'); ?>
              </div>
              <div class="block__amount">
                <?php echo $block->getPureValue(); ?>
              </div>
            </div>
            <div class="input-group d-none">
              <input type="text" class="input-text form-control input-discount" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?php echo $block->escapeHtml(__('Coupon code')); ?>" />
              <span class="input-group-btn">
                <button type="button" class="action cancel primary" value="<?php /* @escapeNotVerified */ echo __('Cancel') ?>">
                  <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                </button>
              </span>
            </div>
          </div>
        <?php endif; ?>
      </div>
    </form>
  </div>
</div>

<script>
  require([
    'jquery',
  ], function($) {
    var couponBlock = document.querySelector('.block.block--new-coupon');
    var removeCouponBlock = document.querySelector('.block.block--remove-coupon');

    if (couponBlock) {
      couponBlock.querySelector('.block__title').addEventListener('click', function() {
        couponBlock.classList.add('is-active');

        window.setTimeout(function () {
          couponBlock.querySelector('.block__input').focus();
        }, 600);
      });
    }

    if (removeCouponBlock) {
      removeCouponBlock.querySelector('.block__amount').addEventListener('click', function() {
        removeCouponBlock.querySelector('.action.cancel').dispatchEvent(new Event('click'));
      });
    }
  });
</script>
