<?php if ($block->hasCartItems()) : ?>
  <div class="block block--cart-total">
    <h1 class="block__title">
      <?php echo __('Your cart total') ?>
      <span class="price"><?php echo $block->getPrice()['grandTotal']; ?></span>
    </h1>
    <span class="block__lead">
      <?php echo __('Net grand total') ?>
      <span class="price"><?php echo $block->getPrice()['subTotal']; ?></span>
    </span>
  </div>

  <script>
    require([
      'jquery',
    ], function($) {
      var cartItems = document.querySelector('.col-form-cart');
      var cartButtons = document.querySelector('.block.block--cart-header-buttons');

      var watchScroll = function() {
        var y = window.scrollY;
        var cartItemsHeight = Number(cartItems.offsetTop + cartItems.offsetHeight - 280);

        if (y >= 280 && y < cartItemsHeight) {
          cartButtons.classList.add('is-under');
        } else {
          cartButtons.classList.remove('is-under');
        }
      };

      window.addEventListener('scroll', watchScroll);
    });
  </script>
<?php endif; ?>
