<table class="data table only-grand-total-incl">
  <tbody>
    <tr class="grand totals incl">
      <td class="mark" colspan="1" scope="row">
        <strong><?php echo __('Order Total Incl. Tax'); ?></strong>
      </td>
      <td class="amount" data-th="<?php echo __('Order Total Incl. Tax'); ?>">
        <strong><span class="price"><?php echo $block->getPrice()['grandTotal']; ?></span></strong>
      </td>
    </tr>
  </tbody>
</table>
