<?php /** @var $block \Oander\ApplePay\Block\Main */ ?>
<?php
$config = [
    'quoteDetailsURL' => $block->getQuoteDetailsURL(),
    //'id' => $id,
    'clientToken' => $block->getClientToken(),
    'displayName' => $block->getMerchantName(),
    'actionSuccess' => $block->getActionSuccess(),
    //'grandTotalAmount' => $block->getAmount(),
    //'isLoggedIn' => $block->isCustomerLoggedIn(),
    'storeCode' => $block->getStorecode(),
    'countryCode' => $block->getCountryCode(),
    'currencyCode' => $block->getCurrencyCode(),
    'displayIn' => $block->getDisplayIn()
];
?>
<div id="applepay-object" data-mage-init='{"applePay": <?php /* @escapeNotVerified */ echo json_encode($config) ?>}'>
<script type="text/javascript">
    require(['jquery'],function($) {
        var selectors = {
            minicart: '[data-block="minicart"]',
            checkoutbutton: '#top-cart-btn-checkout',
            applepayObject: '#applepay-object',
            originallink: '#apple-pay-original-link'
        };

        var minicart = $(selectors.minicart);
        var checkoutlink = '<div id=\'minicar-original-link\'><a id=\'apple-pay-original-link\' href="javascript:jQuery(\'#top-cart-btn-checkout\').trigger(\'click\');">Ez a valós checkout link</a>';
        var applepaycontainer = '<div id=\'minicart-applepay\'></div>';
        minicart.on('contentUpdated', function () {
            var originallink = $(selectors.originallink);
            if (originallink.length === 0) {
                var applePay = $(selectors.applepayObject).data('mageApplepay');
                if(applePay.canUseApplePay('<?php echo \Oander\ApplePay\Enum\DisplayIn::MINICART; ?>')) {
                    var checkoutbutton = $(selectors.checkoutbutton);
                    checkoutbutton.hide();
                    checkoutbutton.parent().append(applepaycontainer);
                    checkoutbutton.parent().append(checkoutlink);
                    applePay.addCartButton(document.getElementById('minicart-applepay'));
                }
            }
        });
    });
</script>