<?php /** @var $block \Oander\ApplePay\Block\Main */ ?>
<?php
$config = [
    "Oander_ApplePay/js/applepay" => [
    'quoteDetailsURL' => $block->getQuoteDetailsURL(),
    //'id' => $id,
    'clientToken' => $block->getClientToken(),
    'displayName' => $block->getMerchantName(),
    'actionSuccess' => $block->getActionSuccess(),
    //'grandTotalAmount' => $block->getAmount(),
    //'isLoggedIn' => $block->isCustomerLoggedIn(),
    'storeCode' => $block->getStorecode(),
    ]
];
?>
<div id="applepay-object" data-mage-init='{"applePay": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>}'></div><script type="text/javascript">
</script>