<?php
/**
 * Oander_MultiSlider
 *
 * @author  David Belicza <david.belicza@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php
/**
 * @see \Oander\MultiSlider\Block\HomeSlider
 * @see \Oander\MultiSlider\Api\Data\ImageInterface
 */
?>
<?php /** @var $this \Oander\MultiSlider\Block\HomeSlider */ ?>
<?php $items = $this->getSliderImages(); ?>
<?php $sliderId = $this->getSliderId(); ?>
<?php $mediaUrl = $this->getMediaUrl(); ?>

<?php if ($items->getSize() > 0) : ?>
    <div class="container oander-multislider">
        <div class="slider-layer loading" id="slider-layer"></div>
        <div class="multislider-inner">
            <div id="<?php echo $sliderId; ?>">
                <?php foreach ($items as $item) : ?>
                    <div class="multislider-item">
                        <a href="<?php echo $item->getLink() ?>">
                            <img src="<?php echo $mediaUrl . $item->getImageMobile() ?>" class="hidden-lg-up" alt="<?php echo $item->getName() ?>" />
                            <img src="<?php echo $mediaUrl . $item->getImage() ?>" class="hidden-md-down" alt="<?php echo $item->getName() ?>" />
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery','oanderMultiSlider'],function($){
        $(document).ready(function() {
            var homeSlider = $('#<?php echo $sliderId; ?>');
            homeSlider.on('init', function () {
                setTimeout(function () {
                    $('#slider-layer').removeClass('loading');
                }, 0);
            });
            homeSlider.slick({
                speed: 300,
                dots: true,
                fade: false,
                autoplay: false,
                autoplaySpeed: 5000,
                prevArrow: '<a href="#" class="slick-prev hidden-sm-down"><span><i class="icon icon-chevron-left"></i></span></a>',
                nextArrow: '<a href="#" class="slick-next hidden-sm-down"><span><i class="icon icon-chevron-right"></i></span></a>'
            });
        });
    });
</script>