<?php
/**
 * Oander_MultiSlider
 *
 * @author  David Belicza <david.belicza@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php
/**
 * @see \Oander\MultiSlider\Block\HomeSlider
 * @see \Oander\MultiSlider\Api\Data\ImageInterface
 */
?>
<?php /** @var $this \Oander\MultiSlider\Block\HomeSlider */ ?>
<?php $items = $this->getSliderImages(); ?>
<?php $sliderId = $this->getSliderId(); ?>
<?php $mediaUrl = $this->getMediaUrl(); ?>

<?php if ($items->getSize() > 0) : ?>
    <div class="container oander-multislider">
        <div class="slider-layer loading" id="slider-layer"></div>
        <div class="multislider-inner">
            <div id="<?php echo $sliderId; ?>">
                <?php foreach ($items as $item) : ?>
                    <div class="multislider-item">
                        <div class="hidden-md-up"><a href="<?php echo $item->getLink() ?>" class="slider-link"><img src="<?php echo $mediaUrl . $item->getImageMobile() ?>" alt="<?php echo $item->getName(); ?>" /></a></div>
                        <a href="<?php echo $item->getLink() ?>" class="slider-link">
                            <div class="image-container hidden-sm-down"
                                 style="background-image: url(<?php echo $mediaUrl . $item->getImage(); ?>)"></div></a>
                        <div class="slider-caption">
                            <div class="row">
                                <div class="text-box col-12">
                                    <p class="slider-caption-inner">
                                        <span class="slider-title"><?php echo $item->getName(); ?></span>
                                        <span class="slider-text"><?php echo $item->getText() ?></span>
                                    </p>
                                    <a href="<?php echo $item->getLink() ?>" class="btn btn-outline-primary text-uppercase">Megnézem</a>

                                    <a href="#" class="slick-prev btn btn-link slick-arrow"><i class="icon icon-chevron-left"></i></a>
                                    <a href="#" class="slick-next btn btn-link slick-arrow"><i class="icon icon-chevron-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery','oanderMultiSlider'],function($){
        $(document).ready(function() {
            var homeSlider = $('#<?php echo $sliderId; ?>');
            homeSlider.on('init', function () {
                setTimeout(function () {
                    $('#slider-layer').removeClass('loading');
                }, 0);
            });
            homeSlider.slick({
                speed: 300,
                fade: false,
                autoplay: false,
                autoplaySpeed: 5000,
                slidesToShow: 1,
                arrows: false
                //prevArrow: '<a href="#" class="slick-prev btn btn-link"><i class="icon icon-chevron-left"></i></a>',
                //nextArrow: '<a href="#" class="slick-next btn btn-link"><i class="icon icon-chevron-right"></i></a>'
            });

            $('.oander-multislider .slick-prev').click(function(e){
                e.preventDefault();
                homeSlider.slick('slickPrev');
            });
            $('.oander-multislider .slick-next').click(function(e){
                e.preventDefault();
                homeSlider.slick('slickNext');
            });
        });
    });
</script>