<?php
/**
 * Oander_WarehouseStockOrder
 *
 * @author  Gabor Kuti <gabor.kuti@oander.hu>
 * @license Oander Media Kft. (http://www.oander.hu)
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Oander\WarehouseStockOrder\Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>

<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><i class="icon icon-arrow-down"></i></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><i class="icon icon-arrow-up"></i></span>
        </a>
    <?php endif; ?>
    <label for="instockfirst" class="custom-checkbox in-stock-first">
        <input type="checkbox" class="custom-checkbox__input" id="instockfirst" name="instockfirst" data-role="instockfirst" <?php echo $block->getInstockFirst() ? 'checked' : '' ?>/>
        <span class="custom-checkbox__text">
            <?php echo __('In stock first') ?>
        </span>
    </label>
</div>
