<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount cart-discount" id="block-discount"
     data-mage-init='{"collapsible":{"openedState": "active", "active": 1, "saveState": false}}'>
    <div class="title hidden-xs-up" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Apply Discount Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?php strlen($block->getCouponCode()) ? ' applied' : ''?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />

                <label for="coupon_code" class="title"> <?php echo __('Do you have a discount coupon?'); ?> </label>
                <div class="input-group">
                    <input type="text" class="input-text form-control input-discount" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?php echo $block->escapeHtml(__('Coupon code'));?>" />
                    <span class="input-group-btn">
                        <?php if (!strlen($block->getCouponCode())): ?>
                            <button class="action apply primary" type="button" value="<?php /* @escapeNotVerified */ echo __('Apply') ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Apply') ?></span>
                            </button>
                        <?php else: ?>
                            <button  type="button" class="action cancel primary" value="<?php /* @escapeNotVerified */ echo __('Cancel') ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                            </button>
                        <?php endif; ?>
                    </span>
                </div>
            </div>
        </form>
    </div>
</div>
