<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Oander\ProductWidgetWarehouseManagerExtender\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $subheadline = $block->getSubheadline() ? __($block->getSubheadline()) : '';
    $link = (strpos($block->getLink(), 'href') !== false) ? $block->getLink() : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list link-extended <?php /* @escapeNotVerified */ echo $mode; ?>" data-items-slider="true">
        <?php if ($title): ?>
            <h2 class="block-title"><?php /* @escapeNotVerified */ echo $title; ?></h2>
        <?php endif ?>
        <?php if ($subheadline):?>
            <h3><?php /* @escapeNotVerified */ echo $subheadline; ?></h3>
        <?php endif ?>
        <?php if ($link):?>
            <?php /* @escapeNotVerified */ echo $link; ?>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="products list product-items row <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php foreach ($items as $_item): ?>
                        <div class="product-item item col-sm-6 col-md-4 col-lg-3">
                            <div class="product-item-info">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>

                                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                   class="product-item-details">
                                    <div class="product-item-name">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </div>
                                    <div class="swatch-attribute color">
                                        <div class="swatch-attribute-options clearfix">
                                            <?php foreach ($block->getColorSwatcherData($_item) as $colorTitle => $colorSwatcher): ?>
                                                <?php if (isset($colorSwatcher['swatchhex'])): ?>
                                                    <div class="swatch-option color" title="<?php echo $colorTitle ?>" option-label="<?php echo $colorTitle ?>" style="background: <?php echo $colorSwatcher['swatchhex'] ?> no-repeat center; background-size: initial;"></div>
                                                <?php endif; ?>
                                                <?php if (isset($colorSwatcher['swatchurl'])): ?>
                                                    <div class="swatch-option color" title="<?php echo $colorTitle ?>" option-label="<?php echo $colorTitle ?>">
                                                        <img src="<?php echo $colorSwatcher['swatchurl'] ?>"/>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        </div>
                                    </div>
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>

                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>
                                </a>
                                <?php if ($productStock = $block->getProductStock($_item)): ?>
                                    <div class="warehouse-in-stock" data-color="<?php echo $productStock->getStockStatus() ?>">
                                        <p><?php echo $productStock->getStockStatusText() ?></p>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <div class="actions-secondary">
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="action outline-primary"><?php /* @escapeNotVerified */ echo __('More info'); ?></a>
                                        </div>

                                        <?php if ($showCart && $_item->getTypeId() === 'simple') : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <i class="icon icon-cart-plus"></i>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <i class="icon icon-cart-plus"></i>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action link towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <i class="icon icon-heart"></i>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
    <script type="text/javascript">
        require([
            'oander.items-slider'
        ]);
    </script>
<?php endif;?>
