<?php $exist = $block->getItems()->getSize() ?>
<?php $items = $block->getItems(); ?>
<?php if ($exist): ?>
    <div class="form-group">
        <select id="dropdown-products-select">
            <option selected value><?php echo __('Select an option'); ?></option>
            <?php foreach ($items as $_item): ?>
                <?php if ($_item->isSaleable()): ?>
                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                    ?>
                    <option value="<?php echo $_item->getId(); ?>" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'><?php echo $_item->getName(); ?>
                        + <?php echo $block->getProductPrice($_item); ?>
                    </option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery', 'dropdownProducts'], function ($, dropdownProducts) {
        dropdownProducts.init()
    });
</script>
