<?php
$_specificInfo = $block->getSpecificInformation();
?>
<?php if (count($_specificInfo) > 0): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <tr>
                <th><?php echo __($block->escapeHtml($_label))?></th>
                <td><?php echo nl2br(implode("\n", $block->getValueAsArray($_value, true)))?></td>
            </tr>
        <?php endforeach; ?>
            <tr>
                <th><?php echo __("Voucher Link"); ?></th>
                <td><?php echo $block->getVoucherLink(); ?></td>
            </tr>
    </table>
<?php endif; ?>
