<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <div class="col-12 col-md-6 col-lg-4">
        <button type="submit" name="do" title="<?php /* @escapeNotVerified */ echo __('Update Wish List') ?>"
                class="btn btn-outline-primary">
            <span><?php /* @escapeNotVerified */ echo __('Update Wish List') ?></span>
        </button>
    </div>
<?php endif;?>
