<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'list';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_list_content_widget';
    $title = __('Recently viewed products');
    $items = $block->getRecentlyViewedProducts();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
}
?>

<?php if ($exist):?>
    <div class="recently-viewed-products-wrapper hidden-sm-down">
        <div class="container">
            <div class="block widget block-viewed-products-<?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="d-flex align-items-center justify-content-end">
                    <div class="mr-auto viewed-products-heading">
                        <h2 class="mr-4"><?php /* @escapeNotVerified */ echo $title; ?>:</h2>
                    </div>
                    <div class="block-content">
                        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                        <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                            <div class="product-items row justify-content-end <?php /* @escapeNotVerified */ echo $type; ?>">
                                <?php foreach ($items as $_item): ?>
                                    <div class="product-item-info mb-3 mb-lg-0">
                                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                           class="product-item-photo tooltip" data-toggle="tooltip"
                                           data-placement="top" title="<?php echo $block->escapeHtml($_item->getName()) ?>">
                                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                        </a>
                                    </div>
                                <?php endforeach ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php endif;?>
