<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getToolbarHtml()): ?>
        <?php echo $this->getToolbarBlock()->setHideToolbar(false)->setHidePagination(true)->toHtml();?>
    <?php endif; ?>

    <?php if (!$this->getHideToolbar()) : ?>
        <div class="toolbar toolbar-products clearfix" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>

            <a href="#" class="btn btn-outline-secondary sidebar-collapse-trigger hidden-md-up" id="sidebar-collapse-trigger">
                <?php /* @escapeNotVerified */ echo __('Filters') ?>
            </a>

            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

            <?php if ($block->isExpanded()): ?>
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php if (!$this->getHidePagination()) : ?>
        <div class="pagination pagination-products">
            <?php echo $block->getPagerHtml() ?>
        </div>
    <?php endif; ?>

<?php endif ?>
