<?php
if ((isset($_GET['tag'])) && ($_GET['tag'] == 'jLhrHYsfPQ3Gu9JgJPLJ')){
    
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	
	if (isset($_GET['oid'])){
		$tbiro_plaintext_64 = $_GET['oid'];
	}else{
		$tbiro_plaintext_64 = "";
	}
	$tbiro_plaintext = base64_decode($tbiro_plaintext_64);
	//var_dump($tbiro_plaintext);

	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
	$tbiro_publicKey = openssl_pkey_get_public(file_get_contents($fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::VAR_DIR)->getAbsolutePath() . 'keys/public.key'));
	$tbiro_a_key = openssl_pkey_get_details($tbiro_publicKey);
	$tbiro_chunkSize = ceil($tbiro_a_key['bits'] / 8) - 11;
	$tbiro_output = '';
			
	while ($tbiro_plaintext) {
		$tbiro_chunk = substr($tbiro_plaintext, 0, $tbiro_chunkSize);
		$tbiro_plaintext = substr($tbiro_plaintext, $tbiro_chunkSize);
		$tbiro_encrypted = '';
		if (!openssl_public_encrypt($tbiro_chunk, $tbiro_encrypted, $tbiro_publicKey)) {
			die('Failed to encrypt data');
		}
		$tbiro_output .= $tbiro_encrypted;
	}
	openssl_free_key($tbiro_publicKey);
	$tbiro_output64 = base64_encode($tbiro_output);
		
	if (isset($_GET['tbiro_envurl'])){
		$tbiro_envurl = $_GET['tbiro_envurl'];
	}else{
		$tbiro_envurl = "";
	}

	if (isset($_GET['tbi_pause_txt'])){
		$tbi_pause_txt = $_GET['tbi_pause_txt'];
	}else{
		$tbi_pause_txt = "";
	}

	?>
	<?php if ($tbiro_envurl != ''){ ?>
		<style>
		#tbiroloaderpanel {
			display: none;
			position: fixed;
			top:calc(100% / 2);
			left:calc(100% / 2 - 200px);
			background: white;
			z-index:999;
			border: 2px solid #f3f3f3;
			width: 400px;
			height: 90px;
		}
		#tbiroloader {
			position: absolute;
			top:10px;
			left:10px;
			border: 16px solid #f3f3f3;
			border-radius: 50%;
			border-top: 16px solid #f07524;
			width: 40px;
			height: 40px;
			-webkit-animation: spin 2s linear infinite; /* Safari */
			animation: spin 2s linear infinite;
		}
		#tbiroloadertext {
			position: absolute;
			top: 0px;
			left: 90px;
			padding:10px;
			width: 100% - 90px;
			font-size: 12px;
			font-weight: bold;
			text-align: center;
			color: #f07524;
		}
		#tbiroloaderimg {
			position: absolute;
			top:45px;
			width: 100%;
			text-align: center;
		}
		/* Safari */
		@-webkit-keyframes spin {
			0% { -webkit-transform: rotate(0deg); }
			100% { -webkit-transform: rotate(360deg); }
		}
		@keyframes spin {
			0% { transform: rotate(0deg); }
			100% { transform: rotate(360deg); }
		}
		</style>
		<div id="tbiroloaderpanel">
		<div id="tbiroloader"></div>
		<div id="tbiroloadertext"><?php echo $tbi_pause_txt; ?></div>
		<div id="tbiroloaderimg"><img src="<?php echo $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'keys/logo.png'; ?>" alt="TBI" /></div>
		</div>		
		<?php }else{ ?>
		<p style="text-align:center;font-weight:bold;font-size:130%;">The Active environment field is empty!</p>
		<?php } ?>
		<script>
			function createCORSRequest(method, url) {
				var xhr = new XMLHttpRequest();
				if ("withCredentials" in xhr) {
					xhr.open(method, url, true);
				} else if (typeof XDomainRequest != "undefined") {
					xhr = new XDomainRequest();
					xhr.open(method, url);
				} else {
					xhr = null;
				}
				return xhr;
			}
		
			<?php if ($tbiro_envurl != ''){ ?>
			var tbiroloaderpanel = document.getElementById("tbiroloaderpanel");
			tbiroloaderpanel.style.display = "block";
			var data = new FormData();
			data.append("order_data", "<?php echo $tbiro_output64; ?>");
			data.append("providerCode", "avast");
			var xmlhttpro = createCORSRequest("POST", "<?php echo $tbiro_envurl; ?>");
			xmlhttpro.onreadystatechange = function() {
				if (this.readyState == 2) {
					var headers = this.responseURL;
					window.location.href = headers;
				}
			};
			xmlhttpro.send(data);
			<?php } ?>
		</script>
		<?php		
}