<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Oander\FanCourierValidator\Block\Address\Edit
 */
?>
    <form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br>
            <?php echo $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
            <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
            <?php echo $block->getNameBlockHtml() ?>
            <div class="form-group field company">
                <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                </div>
            </div>
            <div class="form-group field telephone required">
                <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                <div class="control">
                    <input type="text" name="telephone" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone">
                </div>
            </div>
            <div class="form-group field fax">
                <label class="label" for="fax"><span><?php /* @escapeNotVerified */ echo __('Fax') ?></span></label>
                <div class="control">
                    <input type="text" name="fax" id="fax" title="<?php /* @escapeNotVerified */ echo __('Fax') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
                </div>
            </div>
        </fieldset>
        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend><br>
            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
            <div class="form-group field street required">
                <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="form-control input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>" />
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++) : ?>
                            <div class="form-group field additional">
                                <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i + 1 ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i + 1) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i + 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i + 1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i + 1 ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
                <div class="form-group field taxvat">
                    <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
                    <div class="control">
                        <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($block->isRequiredRegion()) : ?>
                <div class="form-group field region required">
                    <label class="label" for="region"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                    <div class="control">
                        <input type="hidden" id="region_id" name="region_id" />
                        <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="form-control input-text required-entry" />
                    </div>
                </div>
            <?php elseif ($block->isValidateRegion()) : ?>
                <div class="form-group field region required validate">
                    <label class="label" for="region"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                    <div class="control">
                        <?php if ($block->escapeHtml($block->getRegion() == "")) : ?>
                            <span class="region-exist" data-exist="false"></span>
                        <?php endif; ?>
                        <input type="text" class="region hide" name="region" id="region" data-validate='{"required":true}' />
                        <input type="hidden" id="region_id" name="region_id" />
                        <select id="region-list" name="region-list" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="form-control validate-select">
                            <?php $states = $block->getStates() ?>
                            <?php foreach ($states as $state) : ?>
                                <option value="<?php echo $state['value'] ?>" <?= ($state['value'] == $block->escapeHtml($block->getRegion()) ? 'selected' : '') ?>><?php echo $state['label'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php else : ?>
                <div class="form-group field region required">
                    <label class="label" for="region"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                    <div class="control">
                        <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="form-control input-text required-entry" />
                    </div>
                </div>
                <script>
                    require(["jquery"], function($) {
                        var removeDisabled = setInterval(function() {
                            if ($('input[name="region"][disabled="disabled"]').length) {
                                $('input[name="region"]').removeAttr('disabled');
                                clearInterval(removeDisabled);
                            }
                        }, 100);
                    });
                </script>
            <?php endif; ?>

            <?php if ($block->isValidateRegion()) : ?>
                <div class="form-group field city required validate">
                    <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                    <div class="control">
                        <?php $cities = $block->getCities() ?>
                        <div class="cities hidden">
                            <?php foreach ($cities as $city) : ?>
                                <?php if ($city["state"] == $block->escapeHtml($block->getRegion())) : ?>
                                    <div class="city" value="<?php echo $city['value'] ?>"><?php echo $city['label'] ?></div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                        <div class="dropdown dropdown--fc">
                            <div class="dropdown__input">
                                <input type="text" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" name="fc-search" class="dropdown__search form-control" autocomplete="off" <?= ($block->escapeHtml($block->getRegion() == "") ? 'disabled' : '') ?>>
                            </div>
                            <div class="dropdown__selected hidden">
                                <input type="text" name="city" class="city hide" id="city" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" data-validate='{"required":true}' />
                            </div>
                            <div class="dropdown__selected"></div>
                            <div class="dropdown__list">
                                <?php foreach ($cities as $city) : ?>
                                    <?php if ($city["state"] == $block->escapeHtml($block->getRegion())) : ?>
                                        <div class="dropdown__item" value="<?php echo $city['value'] ?>"><?php echo $city['label'] ?></div>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else : ?>
                <div class="form-group field city required">
                    <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                    <div class="control">
                        <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                    </div>
                </div>
            <?php endif; ?>

            <div class="form-group field zip required">
                <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="form-control input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>
            <div class="form-group field country required">
                <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                <div class="control">
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <?php if ($block->isDefaultBilling()) : ?>
                <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
            <?php elseif ($block->canSetAsDefaultBilling()) : ?>
                <div class="form-check field choice set billing">
                    <label class="form-check-label label" for="primary_billing">
                        <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="form-check-input checkbox">
                        <span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span>
                    </label>
                </div>
            <?php else : ?>
                <input type="hidden" name="default_billing" value="1" />
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()) : ?>
                <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?></div>
            <?php elseif ($block->canSetAsDefaultShipping()) : ?>
                <div class="form-check field choice set shipping">
                    <label class="form-check-label" for="primary_shipping">
                        <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="form-check-input checkbox">
                        <span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span>
                    </label>
                </div>
            <?php else : ?>
                <input type="hidden" name="default_shipping" value="1">
            <?php endif; ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
            </div>
            <button type="submit" class="hidden-submit" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
    </form>

<?php if (!$block->isRequiredRegion() && !$block->isValidateRegion()) : ?>
    <script type="text/x-magento-init">
        {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo ($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
        {
        "#form-validate": {
            "validation": {}
        }
    }
</script>
<?php endif; ?>
<?php
if ($block->isValidateRegion()) :
    echo 'van validate';
    $baseUrl = $this->getUrl();
    ?>

    <script>
        require(["jquery"], function($) {
            $(document).on('click', '.field.region .dropdown__item', function() {
                var param = $(this).text();
                $.ajax({
                    showLoader: true,
                    url: "<?php echo $block->getCitiesAjaxUrl() ?>",
                    data: {
                        state: param
                    },
                    type: "GET",
                    dataType: 'json'
                }).done(function(data) {
                    let citiesData = data.cities;
                    let citiesDropdown = $('.field.city').find('.dropdown--fc').find('.dropdown__list');

                    $('.field.city .cities.hidden').html('');
                    citiesDropdown.html('');
                    $('.field.city .dropdown__search').attr('value', '');

                    for (let index = 0; index < citiesData.length; index++) {
                        const element = citiesData[index];

                        citiesDropdown.append('<div class="dropdown__item">' + element + '</li>');
                        $('.field.city .cities.hidden').append('<div class="dropdown__item">' + element + '</li>');
                    }

                    if ($('.field.city .dropdown__search').attr('disabled')) {
                        $('.field.city .dropdown__search').removeAttr('disabled');
                    }

                    $('.field.city .dropdown__item').click(function() {
                        $('.field.city .dropdown__selected input[name="city"]').attr('value', $(this).text());
                        $('.field.city .dropdown__search[name="fc-search"]').attr('value', $(this).text());
                    });

                    $('.field.city .dropdown__search').on('keyup', function() {
                        let searchVal = $(this).val();

                        $(this).closest('.dropdown--fc').find('.dropdown__list').html('');

                        for (let index = 0; index < citiesData.length; index++) {
                            const element = citiesData[index];

                            if (element.indexOf(searchVal) > -1 || element.toLowerCase().indexOf(searchVal) > -1) {
                                $(this).closest('.dropdown--fc').find('.dropdown__list').append('<div class="dropdown__item">' + element + '</div>');
                            }
                        }

                        $('.field.city .dropdown__item').click(function() {
                            $('.field.city .dropdown__selected input[name="city"]').attr('value', $(this).text());
                            $('.field.city .dropdown__search[name="fc-search"]').attr('value', $(this).text());
                        });
                    });
                });
            });

        });
    </script>

<?php endif; ?>
