<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<form class="form-address-edit profile-address-edit ui-card is-loading" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <legend class="legend h2"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend>
        <?php echo $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">

        <?php echo $block->getChildHtml('is_company') ?>
        <div class="profile-address-edit__form">
            <?php echo $block->getNameBlockHtml() ?>
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?php if($childName !== 'is_company'): ?>
                    <?php echo $block->getChildHtml($childName); ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

        <?php if ($block->isDefaultBilling()) : ?>
            <div class="messages">
                <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()) : ?>
            <div class="profile-address-edit__default-checks form-check field choice set billing">
                <label class="form-check-label label" for="primary_billing">
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="form-check-input checkbox">
                    <span><strong><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></strong></span>
                </label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()) : ?>
            <div class="messages">
                <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?></div>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()) : ?>
            <div class="profile-address-edit__default-checks form-check field choice set shipping">
                <label class="form-check-label" for="primary_shipping">
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="form-check-input checkbox">
                    <span><strong><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></strong></span>
                </label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="profile-address-edit__actions actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <button type="submit" class="hidden-submit" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
            <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
        </button>
    </div>
</form>


<script>
    require([
        "jquery",
        "mage/mage",
        'mage/translate',
        'addressCompanyExtend'
    ], function($, $ko, $t, addressCompanyExtend) {
    });
</script>
<script>
     var getAddressAttributesPositions = <?php echo json_encode($block->getAddressAttributesPositions()) ?>;
</script>

<script type="text/x-magento-init">
        {
        "#form-validate": {
            "validation": {}
        }
    }
</script>
