<?php
if($block->getUid()):
?>
    <iframe
            id="motionlab-player" width="640" height="360"
            src="https://api.motionlab.io/videos/<?= $block->getData('campaign_key')?>/<?= $block->getUid()?>"
            frameborder="0" allow="autoplay; encrypted-media"
            allowfullscreen scrolling="no"
    >
    </iframe>
<?php else : ?>
    <?= $block->getNoUidMessage()?>
<?php endif; ?>

<meta property="og:image:url" content="asdasd" />
<meta property="og:image:secure_url" content="asdasd" />