<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright text-center text-lg-left">
    <div class="hidden-md-up">
        <img src="<?php echo $block->getViewFileUrl('svg/iSTYLE-logo-black-red.svg'); ?>" alt="iStyle" width="115"
             class="mb-3" />
    </div>
    <?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
</div>