<div class="col-lg-4 hidden-md-down footer-lang">
    <div class="d-flex align-items-center">
        <i class="icon icon-globe"></i>
        <small class="text">Select your country</small>
    </div>
</div>
<div class="col-lg-4">
    <p class="text-center">Get in touch with us!  about shopping / about service</p>
</div>
<div class="col-lg-4">
    <ul class="footer-social-icons list-inline text-center text-lg-right">
        <li class="list-inline-item"><a href="#"><i class="icon icon-facebook"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="icon icon-twitter"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="icon icon-instagram"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="icon icon-youtube"></i></a></li>
    </ul>
</div>