<div class="footer-links">
    <div class="row">
        <div class="col-lg-6">
            <div class="js-accordion-box">
                <?php echo $this->getChildHtml('footer_links_1'); ?>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="js-accordion-box">
                <?php echo $this->getChildHtml('footer_links_2'); ?>
            </div>
        </div>
    </div>
</div>